-- MySQL Script generated by MySQL Workbench
-- 12/10/15 17:35:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`zip_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zip_info` (
  `zip_code` INT(11) NOT NULL COMMENT '',
  `city` VARCHAR(45) NOT NULL COMMENT '',
  `region` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`zip_code`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`human_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`human_info` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `first_name` VARCHAR(45) NOT NULL COMMENT '',
  `last_name` VARCHAR(45) NOT NULL COMMENT '',
  `zip_code` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `zi_zip_code_fk_idx` (`zip_code` ASC)  COMMENT '',
  CONSTRAINT `zi_zip_code_fk`
    FOREIGN KEY (`zip_code`)
    REFERENCES `mydb`.`zip_info` (`zip_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`doc_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`doc_info` (
  `id` INT(11) NOT NULL COMMENT '',
  `document` INT(11) NOT NULL COMMENT '',
  INDEX `hi_id_fk_idx` (`id` ASC)  COMMENT '',
  CONSTRAINT `hi_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`human_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`depts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`depts` (
  `dept_id` INT(11) NOT NULL COMMENT '',
  `status` VARCHAR(45) NOT NULL COMMENT '',
  `date` DATE NOT NULL COMMENT '',
  `summa` INT(11) NOT NULL COMMENT '',
  `description` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`dept_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cars` (
  `car_id` INT(11) NOT NULL COMMENT '',
  `brand` VARCHAR(45) NOT NULL COMMENT '',
  `model` VARCHAR(45) NOT NULL COMMENT '',
  `number` INT(5) NOT NULL COMMENT '',
  PRIMARY KEY (`car_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dept_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`dept_info` (
  `car_id` INT(11) NOT NULL COMMENT '',
  `dept_id` INT(11) NOT NULL COMMENT '',
  INDEX `d_dept_id_fk_idx` (`dept_id` ASC)  COMMENT '',
  INDEX `c_id_fk_idx` (`car_id` ASC)  COMMENT '',
  CONSTRAINT `d_dept_id_fk`
    FOREIGN KEY (`dept_id`)
    REFERENCES `mydb`.`depts` (`dept_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `c_id_fk`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`car_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`car_info` (
  `id` INT(11) NOT NULL COMMENT '',
  `car_id` INT(11) NOT NULL COMMENT '',
  INDEX `c_car_id_fk_idx` (`car_id` ASC)  COMMENT '',
  INDEX `hi_id_fk_idx` (`id` ASC)  COMMENT '',
  CONSTRAINT `c_car_id_fk`
    FOREIGN KEY (`car_id`)
    REFERENCES `mydb`.`cars` (`car_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `hi_id_fk_2`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`human_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
