-- MySQL Script generated by MySQL Workbench
-- 12/11/15 15:43:59
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`zip_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zip_info` (
  `zip_id` INT(11) NOT NULL AUTO_INCREMENT  COMMENT '',
  `type` VARCHAR(45) NOT NULL COMMENT '',
  `street` VARCHAR(45) NOT NULL COMMENT '',
  `photo` MEDIUMBLOB NULL COMMENT '',
  PRIMARY KEY (`zip_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`find_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`find_info` (
  `find_id` INT(11) NOT NULL AUTO_INCREMENT  COMMENT '',
  `county` VARCHAR(45) NOT NULL COMMENT '',
  `city` VARCHAR(45) NOT NULL COMMENT '',
  `MaxNumOfGuest` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`find_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user1` (
  `id` INT(11) NOT NULL AUTO_INCREMENT  COMMENT '',
  `name` VARCHAR(45) NOT NULL COMMENT '',
  `phone` INT(11) NOT NULL COMMENT '',
  `zip_id` INT(11) NOT NULL COMMENT '',
  `find_id` INT(11) NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `zi_zip_id_fk_idx` (`zip_id` ASC)  COMMENT '',
  INDEX `fi_find_id_fk_idx` (`find_id` ASC)  COMMENT '',
  CONSTRAINT `zi_zip_id_fk`
    FOREIGN KEY (`zip_id`)
    REFERENCES `mydb`.`zip_info` (`zip_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fi_find_id_fk`
    FOREIGN KEY (`find_id`)
    REFERENCES `mydb`.`find_info` (`find_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `login` VARCHAR(32) NOT NULL COMMENT '',
  `id` INT(11) NOT NULL COMMENT '',
  `password` VARCHAR(45) NOT NULL COMMENT '',
  `email` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`login`)  COMMENT '',
  INDEX `user_id_fk_idx` (`id` ASC)  COMMENT '',
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`user1` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
